kind: pipeline
type: docker
name: build-image

steps:
  - name: build-docker-image
    image: plugins/docker
    settings:
      dockerfile: build/Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rfjbraunstingl/datasti-build-image
      tags:
        - latest
        - ${DRONE_COMMIT}

---
kind: pipeline
type: docker
name: build-backend

steps:
  - name: test
    image: adoptopenjdk:11-jdk-hotspot
    when:
      event:
        exclude:
          - promote
    environment:
      DATABASE_URL: mongodb://mongodb:27017
    commands:
      - cd backend
      - ./mvnw clean verify

  - name: build (staging)
    image: adoptopenjdk:11-jdk-hotspot
    when:
      event:
        - promote
      target:
        - staging
    environment:
      QUARKUS_KUBERNETES_REPLICAS: 1
      CONTAINER_REGISTRY:
        from_secret: container-image-registry
      CONTAINER_GROUP:
        from_secret: container-image-group
      CONTAINER_NAME:
        from_secret: container-image-name
      CONTAINER_USERNAME:
        from_secret: container-image-registry-user
      CONTAINER_PASSWORD:
        from_secret: container-image-registry-pass
    commands:
      - ./mvnw clean package -DskipTests=true -Dquarkus.container-image.push=true

  - name: deploy
    image: bitnami/kubectl:latest
    when:
      event:
        - promote
      target:
        - staging
        - production
    environment:
      RFJ_K8S_SERVER:
        from_secret: k8s-server
      RFJ_K8S_TOKEN:
        from_secret: k8s-token
    commands:
      - kubectl apply -f target/kubernetes/kubernetes.yml --namespace $DRONE_DEPLOY_TO --server $RFJ_K8S_SERVER --insecure-skip-tls-verify --token $RFJ_K8S_TOKEN

services:
  - name: mongodb
    image: mongo
